version: "3.9"

services:
  postgres:
    image: pgvector/pgvector:pg15
    container_name: chatbot-postgres
    restart: always
    environment:
      POSTGRES_USER: youssef
      POSTGRES_PASSWORD: 12345
      POSTGRES_DB: chatbot_db
    ports:
      - "5432:5432"
    volumes:
      - chatbot_pgdata:/var/lib/postgresql/data
      - ./init-scripts:/docker-entrypoint-initdb.d
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U youssef"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - chatbot-network

volumes:
  chatbot_pgdata:
    driver: local

networks:
  chatbot-network:
    driver: bridge